id: P006652
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25509
  title: རྩིས་འཁོར་ཤེས་བྱ།
  author: ''
  volumes:
    b6aa70ad5078447592c637b947d00faf:
      image_group_id: I1KG25511
      title: ''
      volume_number: 1
      total_pages: 206
